// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package gocker

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../gocker/templates", "Dockerfile.gocker.plush", "\"RlJPTSBnb2xhbmc6PCU9IG9wdHMuR29WZXJzaW9uICU+CgpFTlYgR08xMTFNT0RVTEU9PCU9IG9wdHMuR29Nb2RzICU+CgpXT1JLRElSIDwlPSBvcHRzLlBhdGggJT4KCkNPUFkgLiAuCgo8JT0gaWYgKG9wdHMuV2l0aERlcCkgeyAlPgpSVU4gZ28gZ2V0IGdpdGh1Yi5jb20vZ29sYW5nL2RlcC9jbWQvZGVwClJVTiBkZXAgZW5zdXJlIC12CjwlIH0gZWxzZSB7ICU+ClJVTiBnbyBnZXQgLXYKPCUgfSAlPgoKUlVOIDwlPSBvcHRzLkdvQ21kKCkgJT4K\"")
}
